Library/Book/urls.py
from django.urls import path
from . import views


app_name = 'Book'
urlpatterns = [
	path('', views.all_Books, name='all_Books'),
	path('<int:id>/<str:name>/', views.book_detail, name='book_detail'),
]

Library/Library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Book.urls', namespace='Book')),
    path('accounts/', include('accounts.urls', namespace='accounts')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
]

Library/Book/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Books(models.Model):
    name = models.CharField(max_length=100)
    auther = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    publish_date = models.DateTimeField(default=timezone.now)
    summary =models.TextField(max_length=500,blank=True)
    price = models.IntegerField(blank=True , default=0)
    photo = models.FileField(upload_to='Book/%Y/%m/%d/', blank = True)    

    def __str__(self):
    		return self.name
    
    def get_absolute_url(self):
    		return reverse('Book:book_detail', args=[self.id, self.name])

Library/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import MyUserManager


class User(AbstractBaseUser):
	email = models.EmailField(max_length=100, unique=True)
	full_name = models.CharField(max_length=100)
	is_admin = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	objects = MyUserManager()
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['full_name']

	def __str__(self):
		return self.email

	def has_perm(self, perm, obj=None):
		return True

	def has_module_perms(self, app_label):
		return True

	@property
	def is_staff(self):
		return self.is_admin

Library/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email', 'full_name')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
			raise forms.ValidationError('passwords must match')
		return cd['password2']

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user


class UserChangeForm(forms.ModelForm):
	password = ReadOnlyPasswordHashField()

	class Meta:
		model = User
		fields = ('email', 'password', 'full_name')

	def clean_password(self):
		return self.initial['password']


class UserLoginForm(forms.Form):
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class UserRegistrationForm(forms.Form):
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
	full_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

Library/Book/views.py
from django.shortcuts import render,get_object_or_404
from .models import Books
from django.core.paginator import Paginator


def all_Books(request):
    all_books=Books.objects.all()
    paginator = Paginator(all_books, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'Book/all_books.html', {'all_books':all_books,'page_obj': page_obj})

def book_detail(request, id , name):
    book=get_object_or_404(Books,id=id,name=name)    
    return render(request, 'Book/book.html', {'book':book})

Library/accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User


def user_login(request):
	if request.method == 'POST':
		form = UserLoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, email=cd['email'], password=cd['password'])
			if user is not None:
				login(request, user)
				messages.success(request, 'you logged in successfully', 'success')
				return redirect('Book:home')
			else:
				messages.error(request, 'username or password is wrong', 'danger')
	else:
		form = UserLoginForm()
	return render(request, 'accounts/login.html', {'form':form})


def user_logout(request):
	logout(request)
	messages.success(request, 'you logged out successfully', 'success')
	return redirect('Book:home')


def user_register(request):
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = User.objects.create_user(cd['email'], cd['full_name'], cd['password'])
			user.save()
			messages.success(request, 'you registered successfully', 'success')
			return redirect('Book:home')
	else:
		form = UserRegistrationForm()
	return render(request, 'accounts/register.html', {'form':form})

Library/Book/templates/Book/all_books.html
{% extends 'base.html' %}

{% block content %}

 <div>
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs"class="card-body" dir="rtl">
      <li class="nav-item"class="card-body" dir="rtl">
        <a class="nav-link active"hret="#" Fstyle="color:red ;"class="card-body" dir="rtl" href="#"> کتاب ها</a>
      </li>
    </ul>
  </div>
  <div class="card-body"class="card-body" dir="rtl" align="right">
        {% for book in page_obj %}
            <img src = "{{book.photo.url}}"  width="100px" height="100px" dir="ltr" align="center">
            <a href="{{ book.get_absolute_url }}" class="card-body" dir="rtl" align="right">{{ book.name }}</a>
            
            <p></p>
        {% endfor %}
    </div>
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}            
            <a href="?page={{ page_obj.previous_page_number }}">قبلی</a>
        {% endif %}

        <span class="current">
            صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">بعدی</a>            
        {% endif %}
    </span>
    </div>
{% endblock %}

Library/Book/templates/Book/book.html
{% extends 'base.html' %}

{% block content %}
    <h3 dir="rtl" align="right">{{ book.name }}</h3>
    <small dir="rtl" align="right" >{{ book.publish_date|timesince }}</small><hr/>
    <p dir="rtl" align="right">{{ book.title|safe }}</p>
    <p dir="rtl" align="right">{{ book.auther|safe }}</p>
    <p dir="rtl" align="right">{{ book.summary|safe }}</p>
    <p dir="rtl" align="right"> قیمت : {{ book.price|safe }}</p> 
    <img src = "{{book.photo.url}}"   width="300px" height="300px" dir="ltr" align="center">
    <form action="#" method="post" dir="rtl" align="right">
        {% csrf_token %}        
        <input class="btn btn-info" type="submit" value="اضافه کردن به سبد خرید">
    </form>
{% endblock %}

Library/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <p>Login page</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>
{% endblock %}

Library/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

Library/templates/base.html
<!DOCTYPE html>
<html dir="ltr" lang="fa">
<head>
<meta charset="UTF-8">
<title>Library</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block custom_tags %} {% endblock %}
</head>
<body>
<nav class="navbar navbar-light" style="background-color: #60128F;"dir="rtl" align="right">

<style>
h1 {
  color: white;
  text-shadow: 2px 2px 4px #000000;
}
</style>
</head>
<body>

<h1>فروشگاه آنلاین 724</h1>
        <a class="btn btn-light btn-sm" href="{% url 'Book:all_Books' %}" role="button">صفحه اصلی</a>
        {% if request.user.is_authenticated %}
            <a class="btn btn-light btn-sm"style="background-color: #60128F;" href="{% url 'accounts:logout' %}" role="button">خروج</a>
        {% else %}
        {% endif %}
          <a class="btn btn-light btn-sm" href="http://127.0.0.1:8000/admin/login/?next=/admin/" role="button">پنل مدیریت</a>


  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-primary"style="background-color: #60128F; type="submit">جستجو</button>
  </form>
</nav>
    
    <div class="jumbotron">  
        {% if messages %}
            {% for msg in messages %}
                <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
            {% endfor %}
        {% endif %}      
        {% block content %} {% endblock %}
    </div>

</body>
</html>